version: "3"
services:
  backend:
    build:
      context: .
      args:
        DATABASE_URL: ${DATABASE_URL:-mysql://user:password@db/TURTLE_BEE}
    ports:
      - "3001:3001"
    volumes:
      - .:/backend
    restart: always
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "TURTLE_BEE"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password12345"
    expose:
      - "3306"
    ports:
      - "3002:3306"
    volumes:
      # So that our database's state is persisted locally
      # - ./mysql-dump:/docker-entrypoint-initdb.d
      # Where our data will be persisted
      - my-db:/var/lib/mysql

# Names our volume
volumes:
  my-db:
